# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Phila.Gov"
license = "GPL-3.0"
licenselink = ""
description = ""
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
