languageCode: "en-us"
title: "City of Philadelphia Digital Standards"
baseurl: "https://cityofphiladelphia.github.io/standards"
params:
  description: "Digtial standards by the City of Philadelphia"
theme: "phila.gov"
contentDir: "site-content"
